# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.

# Allows use container-based infrastructure
sudo: false

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  include:
    - php: 7.1
      env: ANALYSIS='true'
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true


# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always


# Commands to be run before your environment runs.
# Let Travis choose PHPUnit version, ignore lockfile
before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls:^2.1.0
  - composer install --no-scripts --no-suggest --no-interaction

# Commands you want to run that will verify your build.
script:
  - if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpcs ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpstan analyse src; fi

after_success:
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi


