# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.3
# Allows use container-based infrastructure
sudo: false

# Commands to be run before your environment runs.
# Let Travis choose PHPUnit version, ignore lockfile
before_script:
  - composer self-update
  - composer install --no-scripts --no-suggest --no-interaction

# Commands you want to run that will verify your build.
script:
#  - phpunit


# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.3
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always