version: "3.1"
services:
  php:
    build:
      context: ./docker/php
    working_dir: /var/www
    command: php -S 0.0.0.0:80 -t public
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    expose:
      - 80
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pando
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  composer:
    image: composer
    volumes:
      - .:/app
      - ~/.composer:/tmp

volumes:
  logs:
    driver: local